services:
  caddy:
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile.prod", "--adapter", "caddyfile"]
    ports: !override
      - "80:80"
      - "443:443"

  blog:
    environment:
      BLOG_BASE_URL: https://${SITE_DOMAIN}

  outline:
    environment:
      ALLOWED_PRIVATE_IP_ADDRESSES: 172.29.88.0/24
